### ISSUE TITLE
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression /error

### ISSUE THREAD

**Issue by Nagisa-Kawashima** [Nagisa-Kawashima/java_app#4]
現在上記を含めて３つのエラーが出ており、調べてみると値の引き渡しがうまく出来ていないことによるエラーとのことで、インターネットにアクセスすると、viewが表示されずに、エラー文が出ている状態です。
該当箇所の値の訂正を何度か試みたのですが、エラー内容が依然として変わりません。

現在抱えている疑問点については、Motoscontroller内にてインスタンスを２つ作成すると、動画講座の通りにならずに自動変換でキーの末尾に２がついてしまい、そこで、自動修正を促す文章が発生する為に、自動修正をかけると、
Motorcycle.java　にて下記のようなコンストラクタが作成されてしまいます。
javaの基礎は勿論のこと、javaでアプリ開発を試みるのは初めてであるため、基本的なデータの受け渡しの流れはあまり理解できておりません。
よろしければご教授いただけますと幸いです。

`  public Motorcycle(int motoNo2, String motoName2, int seatHeight2, int cylinder2, String cooling2, int price2,
            String comment2, Brand brand2, int version2, Object insDt2, Object updDt2) {
    }`

開発環境：Vscode
JDK:AdoptOpenJDK
JRE: java SE-17
↓インストールしているバージョン
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

-------------------------------------------------------------------------------------------------------------------
該当エラー文
①　Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "brand.brandName" (template: "moto_list" - line 83, col 21)
②　Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "brand.brandName" (template: "moto_list" - line 83, col 21)　
③　Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'brandName' cannot be found on null　
--------------------------------------------------------------------------------------------------------------------------------
エラー発生の箇所だと思われる部分

> moto_list.html

`<tbody>
              <tr th:each ="moto : ${motos}" th:object ="${moto}">
                <th scope="row" th:text="*{motoNo}"></th>
                <td th:text="*{brand.brandName}"></td>
                <td th:text="*{motoName}"></td>
                <td th:text="*{cooling} + *{cylinder}"></td>
                <td th:text="*{price}"></td>
                <td th:text="*{comment}"></td>
              </tr>
            </tbody>`
------------------------------------------------------------------------------------------------------------------------------------
作成したコード(controller, view等)

**MotosController.java**
[https://drive.google.com/file/d/1H086KEsH7ZsSTYcIoQ3i5YNCVGOXKnrE/view?usp=share_link](url)

 **Motorcycle.java**
[https://drive.google.com/file/d/1E_hbo_Ii9cYbve2Qfj3H3c81h8yDUyYj/view?usp=sharing](url)

**Brand.java**
[https://drive.google.com/file/d/1GJN8TY9JhwnAMiDoxxfivpZHOFC40IF1/view?usp=sharing](url)

**Comment by HyunwookPark** [comment]
@Nagisa-Kawashima 
改めまして、朴と申します。
ご質問ありがとうございます。

> キーの末尾に２がついてしまい

これはコンストラクタの仮引数の後ろに`2`というが付与されてしまうということですね。
インスタンスを作るだけでそうなることはないのですが不思議ですね。

> 下記のようなコンストラクタが作成されて

コンストラクタのつくりが意識的ではない部分がよくないように思います。
エラー内容としてはThymeleafのテンプレートつまり`moto_list.html`にて`brandName`の値が取得できなかったという現象のようですね。

答えを示してもよいですが、
まずはヒントだけを出してみますね。

## ヒント

moto_list.htmlでは`brand.brandName`と指定していて、Motorcycleのオブジェクトから情報を取得しようとしています。
ソースコード上でそれができるかどうかを辿ってみてください。
ご自分で原因を見つけて解決できるのを期待しています😊

**Comment by HyunwookPark** [comment]
@Nagisa-Kawashima 
具体的にエラー内容とソースコードを貼ってくれたのはとてもナイスです！

できれば実際のファイルを貼るかgithubにpushされた状態にしてブランチを連携してくれると
質問としては100点満点になりそうです♪
